elepwr <- read.table("household_power_consumption.txt",sep=";")
names(elepwr) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
subelepwr <- subset(elepwr,elepwr$Date=="1/2/2007" | elepwr$Date =="2/2/2007")
png("plot3.png", width=480, height=480)
datetime <-strptime(paste(subelepwr$Date, subelepwr$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
plot(datetime,subelepwr$Sub_metering_1, type = "n", ylab = "Energy sub metering", xlab = "")
lines(datetime,subelepwr$Sub_metering_1, col = "black")
lines(datetime,subelepwr$Sub_metering_2, col = "red")
lines(datetime,subelepwr$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()